# Generated by Django 4.2.7 on 2023-12-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_male_clothes_product_female_clothes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
