# Generated by Django 4.2.7 on 2023-12-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_female_clothes_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='female_clothes',
        ),
    ]
